test/feature: Signal failure with nonzero exit code from the script.

diff --git a/tests/features/featuretest b/tests/features/featuretest
--- a/tests/features/featuretest
+++ b/tests/features/featuretest
@@ -4,13 +4,14 @@
 # build or runtime failures.
 
 skipped_features="TCP_NSC VoIPStream"
+exitcode=0
 
 # test procedure that is run for each test case (assumes to be in INET_ROOT)
 runtest() {
-  (make makefiles >/dev/null && make cleanall >/dev/null && make makefiles >/dev/null) || { echo "*** $1 prepare build: FAIL" ; return; }
-  make -j8 >/$LOG_DIR/$1-build.out 2>/$LOG_DIR/$1-build.err || { echo "*** $1 building: FAIL" ; return; }
-  (cd $DIR; opp_run -l ../../src/INET -u Cmdenv -n ../../src:. >/$LOG_DIR/$1-run.out 2>/$LOG_DIR/$1-run.err) || { echo "*** $1 running: FAIL" ; return; }
-  echo "*** $1: PASS"
+  (make makefiles >/dev/null && make cleanall >/dev/null && make makefiles >/dev/null) || { echo "*** $1 prepare build: FAIL" ; return 1; }
+  make -j8 >/$LOG_DIR/$1-build.out 2>/$LOG_DIR/$1-build.err || { echo "*** $1 building: FAIL" ; return 1; }
+  (cd $DIR; opp_run -l ../../src/INET -u Cmdenv -n ../../src:. >/$LOG_DIR/$1-run.out 2>/$LOG_DIR/$1-run.err) || { echo "*** $1 running: FAIL" ; return 1; }
+  echo "*** $1: PASS"; return 0;
 }
 
 cd `dirname $0`
@@ -28,6 +29,7 @@ fi
 # test with all features disabled
 ./inet_featuretool -q disable -f all
 runtest all_disabled
+if [ $? != 0 ]; then exitcode=1; fi
 
 # test with default features enabled (except skipped ones)
 ./inet_featuretool -q reset
@@ -35,6 +37,7 @@ if [ -n "$skipped_features" ]; then
   ./inet_featuretool -q disable -f $skipped_features
 fi
 runtest default
+if [ $? != 0 ]; then exitcode=1; fi
 
 # test with all features enabled (except skipped ones)
 ./inet_featuretool -q enable -f all
@@ -42,6 +45,7 @@ if [ -n "$skipped_features" ]; then
   ./inet_featuretool -q disable -f $skipped_features
 fi
 runtest all_enabled
+if [ $? != 0 ]; then exitcode=1; fi
 
 # test with each feature enabled - one by one
 for feature in $base_features; do
@@ -51,6 +55,7 @@ for feature in $base_features; do
     ./inet_featuretool -q disable -f all
     ./inet_featuretool -q enable -f $feature
     runtest ${feature}_enabled
+    if [ $? != 0 ]; then exitcode=1; fi
   fi
 done
 
@@ -65,5 +70,8 @@ for feature in $base_features; do
   else
     ./inet_featuretool -q disable -f $feature
     runtest ${feature}_disabled
+    if [ $? != 0 ]; then exitcode=1; fi
   fi
 done
+
+exit $exitcode
