featuretest: colorized output

diff --git a/tests/features/featuretest b/tests/features/featuretest
--- a/tests/features/featuretest
+++ b/tests/features/featuretest
@@ -31,12 +31,16 @@ exitcode=0
 
 testindex=0
 
+
 # test procedure that is run for each test case (assumes to be in INET_ROOT)
 runtest() {
-  (make makefiles >/dev/null && make cleanall >/dev/null && make makefiles >/dev/null) || { echo "*** $testindex. $1 prepare build: FAIL" ; return 1; }
-  make -j8 >/$LOG_DIR/$1-build.out 2>/$LOG_DIR/$1-build.err || { echo "*** $testindex. $1 building: FAIL" ; return 1; }
-  (cd $DIR; opp_run -l ../../src/INET -u Cmdenv -n ../../src:. >/$LOG_DIR/$1-run.out 2>/$LOG_DIR/$1-run.err) || { echo "*** $testindex. $1 running: FAIL" ; return 1; }
-  echo "*** $testindex. $1: PASS"; return 0;
+  RED='\033[0;31m'
+  GREEN='\033[0;32m'
+  NC='\033[0m' # No Color
+  (make makefiles >/dev/null && make cleanall >/dev/null && make makefiles >/dev/null) || { echo "*** $testindex. $1 prepare build: ${RED}FAIL${NC}" ; return 1; }
+  make -j8 >/$LOG_DIR/$1-build.out 2>/$LOG_DIR/$1-build.err || { echo "*** $testindex. $1 building: ${RED}FAIL${NC}" ; return 1; }
+  (cd $DIR; opp_run -l ../../src/INET -u Cmdenv -n ../../src:. >/$LOG_DIR/$1-run.out 2>/$LOG_DIR/$1-run.err) || { echo "*** $testindex. $1 running: ${RED}FAIL${NC}" ; return 1; }
+  echo "*** $testindex. $1: ${GREEN}PASS${NC}"; return 0;
 }
 
 cd `dirname $0`
