prod: updates setenv error detection. Try to prevent executing the setenv script.

diff --git a/setenv b/setenv
--- a/setenv
+++ b/setenv
@@ -1,22 +1,13 @@
-#! /bin/sh
-
-case "$-" in
-*i*) ;;
-*)  if [ "$1" != "-f" ]; then # allow use from scripts, as ". setenv -f"
-        echo "Error: not a login shell -- run this script as 'source setenv' or '. setenv'"
-        exit 1
-    fi
-esac
+#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"
 
 if [ ! -f bin/inet ]; then
     echo "Error: current working directory does not look like an INET root directory"
     # no exit -- it would close the shell
 else
-    export INET_ROOT=`pwd`
+    export INET_ROOT=$(pwd)
     echo $INET_ROOT
     export PATH=$INET_ROOT/bin:$PATH
     export INET_OMNETPP_OPTIONS="--image-path=$INET_ROOT/images"
     export INET_GDB_OPTIONS="-quiet -ex run --args"
     export INET_VALGRIND_OPTIONS="-v --tool=memcheck --leak-check=yes --show-reachable=no --leak-resolution=high --num-callers=40 --freelist-vol=4000000"
 fi
-
